### ISSUE TITLE
Species list entry additional columns

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#10]
From the specification:
It would be useful if there was a way to make some columns standard and some additional – i.e. columns that could be expanded/selected if required (e.g. sensitivity*). We can decide which columns will be standard and which additional later (unless the developer needs this now in order to code it efficiently). It would, however, be good if the underlying code was flexible, in that the status of columns (i.e. standard or additional) might change over time and between websites. Columns would be selected from a standard list (i.e. user-specified columns are not allowed).

See #3 for umbrella issue

**Comment by DavidRoy** [comment]
Could this be met from the functionality deployed on Pantheon, although in that context it is for a reporting grid (not an input grid)?

**Comment by johnvanbreda** [comment]
I think this requirement maps quite closely to code we already have in place for making the input grid "responsive". This means that the grid will respond appropriately by changing its layout/behaviour when on a smaller screen. I've enabled this feature now, so, for example if you reduce your browser's width you'll notice the Comment column disappears and reduce it further to see other columns disappear. When you then enter a species, there is a plus button which allows you to access these additional fields. 

So, my suggestion is to add any additional columns you'd like to support to the grid, but prioritise them ourselves so the less frequent ones are not shown until you click +. We could set a cut off point larger than the typical screen so that for normal use the least likely columns to be used will always be hidden until you click +.

This approach does not give per-user customisation, but it might not be necessary? If it is, then it might be more efficient to allow them to alter which columns appear under the + button than to code something entirely new.

**Comment by DavidRoy** [comment]
Agreed.  I suggest we review column priorities after testing

**Comment by sacrevert** [comment]
This approach seems to be exactly what is required. Thanks!

Can we make the current standard column 'Sensitivity' an 'additional column' when the column responsiveness is programmed.

**Comment by johnvanbreda** [comment]
That's done. Sensitivity, altitude and comment are currently set to hide unless you click + at all screen sizes.

**Comment by sacrevert** [comment]
+ icon not appearing on my screen (Chrome), although functionality works.

**Comment by johnvanbreda** [comment]
@sacrevert Which icon do you mean? The + symbol only appears in the right column of the row when you've added a species name. It seemed to work for me on Chrome.

**Comment by sacrevert** [comment]
@johnvanbreda OK, fine, I thought it would be there without adding a species. No problem.
