### ISSUE TITLE
Upload pages for herbarium specimens and literature records.

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#11]
From the specification:
As TH has already commented (email to KJW 16/5/2016), herbarium specimens and literature records contain a number of extra fields. I suggest that we create specific upload pages for these record types – these pages would only allow for the upload of sets of records, and would set out a template to be adhered to. 

See #3 for umbrella issue.

**Comment by johnvanbreda** [comment]
Please can I have a list of fields for herbarium and literature records.

**Comment by sacrevert** [comment]
@DavidRoy @johnvanbreda hi john, thanks for confirming that this is not a big task, and is possible. This idea was not developed to any great extent in the spec, nor in conversation with the BSBI; so, I think this is something that we will now seek more input into from Kevin Walker and Tom Humphrey.

Noting here that coding may be needed for proper treatment of vague dates (alternative appears to be free text field + advice).

**Comment by sacrevert** [comment]
Closing here as this repo deprecated
