### ISSUE TITLE
Vascular plant card grid ref warnings included in review

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#14]
From the spec:
TH suggests that “the system should immediately reject precise gridrefs that fall outside the survey gridsquare”; to me, that seems rather too restrictive, given that I expect a reasonable number of recorders will record occasional records outside of the target grid square – perhaps a compromise could be that records edited to be outside of the grid square could generate a ‘exclamation mark’ warning flag ?

This is now done, but the warnings also need to show on the review page.

See #3 for umbrella issue.

**Comment by johnvanbreda** [comment]
Fixed in the code, pending the next feature update on iRecord.

**Comment by DavidRoy** [comment]
Warning flag still does not appear in review tab

**Comment by johnvanbreda** [comment]
Now fixed. Please close if OK.

**Comment by japonicus** [comment]
Grid reference outlier warnings might need to be re-evaluated if the grid-reference for the card is changed.  It's currently possible to enter records with compatible gridrefs, then change the card-level gridsquare, leaving the records are still marked as valid.
Obviously that's not a normal workflow, but it might happen e.g. if a user gets confused and jumps between cards.

**Comment by johnvanbreda** [comment]
Fixed in the code and will be deployed at the next feature release.
