### ISSUE TITLE
Occurrence attributes do not follow through to review tab

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#15]
Via testing.  This is the plant records tab, not the status field values
![image](https://cloud.githubusercontent.com/assets/2699478/19276809/807a3a6a-8fcf-11e6-85f4-9c9898e84773.png)

Resulting review tab does not pick up correct status values (that we copied down the grid automatically)
![image](https://cloud.githubusercontent.com/assets/2699478/19276859/a572c01c-8fcf-11e6-8fc3-3ed524c70425.png)

**Comment by johnvanbreda** [comment]
This bug is fixed in the code already - commit https://github.com/Indicia-Team/media/commit/928b85b50c7dfedfc0bbd68ace549745561a949f. I'll apply the fix at the next iRecord code update, hopefully in the next few days.
