### ISSUE TITLE
Changes to 'Review and submit tab'

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#16]
#3 Occurrence attributes should be left blank, rather use text = 'undefined'

Species column values currently say 'undefined' even though species are given in the grid.

If you add a habitat as sample attribute, it does not have a label on the 'review' tab

**Comment by johnvanbreda** [comment]
These issues are all fixed in the code, pending the next feature update on iRecord.

**Comment by johnvanbreda** [comment]
Now applied to iRecord. Please close if OK.
