### ISSUE TITLE
Add overview map to Review and submit page

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#18]
#3 It would be nice to add an overview visualisation map to the Review and submit page, particularly if we are allowing people to enter precise grid refs outside of the selected monad/tetrad.

**Comment by johnvanbreda** [comment]
Committed the code for this - will be applied in the next feature update for iRecord.

**Comment by johnvanbreda** [comment]
Now applied to iRecord. Please close if OK.
