### ISSUE TITLE
Save to basket functionality

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#21]
From the spec:
"As well as the ‘submit’ button, there should also be an option to ‘save to basket’, i.e. to save the data entry process for later editing. (One might want to complete entering a list later, or save it until confirmatory information for some species was obtained.)

Area for comment: caching data offline - AvB indicated that this might present some challenges. It seemed (from discussions at the BSBI Records & Research Committee) that this might be useful for those in slow internet areas, or when working away from home without an internet connection (as might happen on field work), but is it worth the effort at this point? More to the point, do we have the funds/time to achieve it within the initial phase of this project?"

Nested in #3

**Comment by johnvanbreda** [comment]
1. For the Save to Basket function, will this allow a form to be saved with some parts of the form incomplete, i.e. does it need to bypass validation for required fields? Or, is it just the same as saving the form with all validation applied, but flagging the form up as unfinished so it doesn't appear on public reports yet, allowing you to browse a list of unfinished forms to edit at a later date? The latter is fairly simple but the former is more complex.
2. Note that there are various aspects of the form which require an internet connection, e.g. the map and species name lookup. Therefore for a fully offline experience we will need to implement quite a few changes which makes me think that a modified version of the iRecord app might be better? Note that potentially we can set the app code up to run via a browser so you aren't forced to use a phone. 
An alternative might be to simply cache the current state of the form in the browser. Then if you accidentally pressed back or lost your connection somehow then when you reload the form it could show a message like "It appears you were previously entering some records that were never submitted. Would you like to reload them to edit?"

**Comment by DavidRoy** [comment]
In response.
1. The simpler option is needed.  same as saving the form with all validation applied, but flagging the form up as unfinished so it doesn't appear on public reports yet, allowing you to browse a list of unfinished forms to edit at a later date? 
This does raise a question about how a user finds this 'sample' form again.  Does it raise the need for the ability to explore samples?

2. I suggest we separate this issue.  It is not an immediate requirement, and the App might be a better place to provide this functionality

**Comment by johnvanbreda** [comment]
1. Agreed. There would need to be a list of unfinished forms available for you to browse. Other ideas include:

   - sending a notification if there are unfinished forms left around for more than, say, 1 month.
   - allowing admins to browse all unfinished forms and either "finish" them or delete them.

Are either of these ideas essential to meet the basic requirement?

**Comment by DavidRoy** [comment]
I think it is essential to have a way for users to browse their 'unfinished forms'.  The other requirements are not essential at the moment.

**Comment by sacrevert** [comment]
I agree with all the above. I note that Tom Humphrey might need to make changes to his DDb sync so that forms flagged as unfinished are not synced. I'm going to send the demo and the github issues to him and Kevin today for comment anyway.

**Comment by sacrevert** [comment]
Split to #64 (essential) and #65 (enhancement)
