### ISSUE TITLE
Location search not working on plant data entry form

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#22]
@johnvanbreda

on http://www.brc.ac.uk/irecord/enter-vascular-plants, when entering a place to search for under 
**'Or search for a place on the map:'** and clicking on the search button, nothing happens.

This functionality is working on other iRecord input forms
#3

**Comment by johnvanbreda** [comment]
fixed by switching form to Google Maps Search API rather than GeoPlanet.
