### ISSUE TITLE
Plant records tab no longer showing grid ref of location being entered

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#23]
#3 @johnvanbreda

As an example.  This is the first tab:
![image](https://cloud.githubusercontent.com/assets/2699478/19443029/585c0672-9483-11e6-8c40-73636335e758.png)

This is the second tab.  Note 'You are entering records for .'
![image](https://cloud.githubusercontent.com/assets/2699478/19443063/770f6f82-9483-11e6-883a-8081e34e9742.png)

**Comment by johnvanbreda** [comment]
It only worked for typed in grid refs, not clicks on the map. Now fixed for both.
