### ISSUE TITLE
Review map zooms too far

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#24]
Under #3 

I think it would be preferable that if records are outside of the monad/tetrad, then, as well as the warning flag, the map on the review page zoomed to the minimal area that bounds all records, including those that are outside of the target square. This would help in assessing errors (e.g. a recorder may enter both mistakes and intentional records outside of the grid square.)

**Comment by DavidRoy** [comment]
@johnvanbreda

I think it behaves this way?

An additional request is that the grid squares for the detailed grid references have a solid line for their boundary - not dashed lines as currently implemented.  I think this is clearer.

**Comment by sacrevert** [comment]
Sorry, yes, my example wasn't extreme enough to make it obvious.
