### ISSUE TITLE
Number of recorders field

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#25]
In addition to the time spent recording, and the ability to enter recorder names separately, should we also capture the number of recorders? It seems a simply thing to do, and so we might as well do it now. The reason why this might be needed in addition to the number of names, is that often, on natural history society meetings, not all names are known, or only the leaders names are entered as recorders (e.g. in the BBS database large groups often associated with spring or summer meetings are often simply entered as 'BBS Summer Meeting', or with the main recorders names only, and everybody else as et al., removing the direct link between names and number of recorders in a recording party. If created it should be a mandatory field. @DavidRoy @johnvanbreda

Nested under #3

**Comment by DavidRoy** [comment]
In principle 'yes' to this.  I'm a little concerned about over-complicating the form with too many mandatory fields.  It would also be good to clarify a few things.
1. would the field be numeric or does it need to cover vague numbers (~10, 10+, 10-15 etc)
2. could it be mandatory but default to a value such as ('1', or 'not recorded').

**Comment by sacrevert** [comment]
how about 1, 2, 3-5, 6-10, 10-20. 20+ ? 
Or, we can consult with Kevin etc. first?

**Comment by DavidRoy** [comment]
I suggest we (@johnvanbreda !) implement these categories and then seek comment.  Default value = 1.

**Comment by sacrevert** [comment]
Safer to have default as blank but insist on change to submit?

**Comment by DavidRoy** [comment]
OK, but we need to be alert to danger of annoying submitters by having too many compulsory fields?

**Comment by sacrevert** [comment]
I'll ask Kevin etc. to comment on this when I email. I don't know how demanding, e.g. MapMate currently is. The BBS spreadsheets have a lot of detail, but, admittedly, they are not so widely used as this will be. I suppose simplifying in response to user feedback in the future is also not a big task.

**Comment by johnvanbreda** [comment]
I've added a number of recorders field with categories as suggested (adjusted slightly to avoid overlaps). It's mandatory and has no default.
