### ISSUE TITLE
Behaviour of iRecord plant input form when not logged in

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#26]
The form should behave as follows when access by a user who is not logged in.

The page should display a message to say
 'To enter records using this form you require an iRecord user account and be logged into the system.  To login or register an iRecord account, please click [here](http://www.brc.ac.uk/irecord/user).

Nested in #3

**Comment by johnvanbreda** [comment]
We don't have an easy way of displaying a custom access denied page on different pages so I've enabled the standard one. Is that OK?

**Comment by DavidRoy** [comment]
yes, ok
