### ISSUE TITLE
Could 'quantity' be added as an additional record attribute?

### ISSUE THREAD

**Issue by kwal2** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#27]
It would be useful to have 'quantity' as an additional attribute of a record on the Plant Record page

**Comment by sacrevert** [comment]
This would presumably be an additional option (i.e appears only when chosen by surveyor clicking +).

Can you specify the categories of the broken log scale that you want?

Nested in #3

**Comment by kwal2** [comment]
Yes, an additional option. I think I would prefer a free-numeric field rather than categories.

**Comment by DavidRoy** [comment]
@kwal2 just to check, are you suggesting an exact number field?

**Comment by kwal2** [comment]
I'm in two minds. I often want to include DAFORs or 'abundant' and increasingly we might start to record cover (as a %). Could there be an option for quantity_numeric (for counts) and quantity_text which could includes a dropdown for DOMIN, DAFOR or is that getting too complicated?

**Comment by japonicus** [comment]
Could a single text field be used for this which could be assigned
automatically (by client-side javascript) to the relevant attribute?

i.e.

unqualified numbers go to a count field
n% is treated as % cover 
DAFOR single-letter codes
'D1' to 'D10' treated as domin

(anything else flagged as invalid)

this would be simple and efficient from a data-entry perspective (would
avoid cluttering the form with an 'abundance type' menu) and ought not to
be too complex to implement.

**Comment by DavidRoy** [comment]
I agree we probably do need options to cover all bases.  

John can comment on the effort to implement as Tom suggests, or Tom could take on the client-side javascript coding.

The danger of allowing free-text is you'll get things such as '10-20', '~6', 'common' as well as standard DAFOR terms (if we are lucky).  The question is whether to allow free text and all the variants that will generate

To be any real use for modelling it needs to be standardised such as. 
1. DAFOR drop-down
2. Numbers

If you are happy for it be a more descriptive field then free text is fine, but accept that without a lot of subsequent cleaning it will be less quantifiable..

**Comment by japonicus** [comment]
I think free text would be bad, for the reasons you mention.

My suggestion was to have 'free-text' only in the sense that the user doesn't need to pre-select the type of entry they're making, but entries would be validated before submission.  '10-20', '~6', 'common' would be rejected.

**Comment by DavidRoy** [comment]
Agreed.  Good solution but we are unlikely to have the funds/time to implement immediately.  Unless it is straightforward using existing Indicia functionality

**Comment by johnvanbreda** [comment]
I think we can use a single free text field but add a regex to the field which validates to allow any of the following options:
any zero or positive integer number
D1 - D10
D, A, F, O or R
0% through to 100%
This is relatively easy to code in Indicia and a bit quicker to implement than using script to map the inputs to different attributes. Any analysis could easily detect which type of value it is by pattern matching.
Is that OK?

**Comment by DavidRoy** [comment]
Good solution and ok by me. Kevin might want to add more regular expressions but hopefully not many

**Comment by kwal2** [comment]
D+ for Domin
LA - locally abundant

**Comment by sacrevert** [comment]
I don't really see the point of the % cover or Domin options, without a specified spatial scale they are meaningless. DAFOR is a bit like this too, although at least there one has the option of interpreting it relative to the area surveyed (although likely this will often not be the correct interpretation).

I would recommend sticking with allowing the DAFOR terms + LA and numeric values, or even just DAFOR. The more heterogeneous the field contents the less likely it will be used for anything, plus enforcing one system encourages its wide use and therefore potentially some unity in how it is used within the BSBI. The PlantPortal (in development) will provide a framework for recording actual plot data if required.

**Comment by kazlauskis** [comment]
Hi, any thoughts on when the abundance will be added in? I am planning to adding a plant specific recording form on the iRecord App and link it to this form on the website.

**Comment by DavidRoy** [comment]
I think Kevin should give the decision on this

**Comment by kwal2** [comment]
OK. Reading the thread I think the consensus is
any integer number
D, A, F, O, R, LA
I agree with Oli that %cover or domin are fairly meaningless with a spatial scale and 99.9% of time are applied to quadrats.

**Comment by japonicus** [comment]
Based on records in the DDb, LF (89 000 records) is a more widely applied term than LA (25 000 records). Is there a practical difference between the two or is this just down to personal preference? (the other local-dafor codes have very low usage)

Is there a need for absent/looked-for-and-not-found or is that too problematic to implement correctly (or to interpret meaningfully)?

**Comment by sacrevert** [comment]
In theory there is a difference between LA and LF. Probably worth adding if it is used that frequently.

My personal inclination is to steer clear of negative records. Looked-for-and-not-found can be inferred anyway if they tick 'full survey' (or whatever the suggestion was).

**Comment by DavidRoy** [comment]
Sally Rankin suggests that categories used in Rose might be useful:
abs – absent – useful, e.g. for when actively searching for a plant that was known to be present in the past, but should only be interpreted as ‘not found on dd/mm/yyyy’
c – common
f – frequent
l – local
la – locally abundant
o – occasional
r – rare
vc – very common
vla – very locally abundant
vr – very rare

**Comment by sacrevert** [comment]
In practice the 'very' additions are not really that useful, plus the DAFOR scale is more widely used than any custom scale, and more familiar to those with any ecological training or consultancy experience. In addition to that, Rose is probably now less widely used than previously, what with the Collins guide and the photographic one from Harrap.

As I said, I'm not that keen on absence records, because they will almost inevitably cause problems for analyses at some point, for someone, somewhere. Plus absence can be inferred if someone claims they attempted a complete survey (although I appreciate that this might not be as informative as a targeted search for one species in a small area that resulted in an absence.) Of course, up to Kevin in the final instance - he may disagree.

**Comment by kwal2** [comment]
I agree with Oli. the extra codes just add more confusion. Lets stick with integers or DAFOR plus LA and LF.

**Comment by johnvanbreda** [comment]
Is that a decision? The spec I think is:

1. Add an optional abundance field to the fields available for input under the + button.
2. Make this a free text datatype, but use a regular expression to enforce one of the options below:
  - D, A, F, O, R (= a DAFOR value)
  - LA or LF (locally abundant or frequent)
  - an integer for a count

**Comment by sacrevert** [comment]
Yes. Thanks John.

**Comment by johnvanbreda** [comment]
Done
