### ISSUE TITLE
Charophytes/Lycopods need to be added to the taxon table

### ISSUE THREAD

**Issue by kwal2** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#28]
BSBI recorders tend to record Charophytes along with vascular plants and so these need adding to the taxon dictionary.

**Comment by sacrevert** [comment]
#3

**Comment by johnvanbreda** [comment]
The list of species available are limited by output group - currently the following are available:
flowering plant
conifer
fern
horsetail
ginkgo
Please confirm which additional output groups you'd like included.

**Comment by sacrevert** [comment]
I presume they are named as following:
stonewort
clubmoss
although I am guessing based on the 'informal groups' in the old BRC database

**Comment by johnvanbreda** [comment]
Those are fine - I've added them to the form. Please close if OK.
