### ISSUE TITLE
Nomenclature is Stace edition 2 not 3

### ISSUE THREAD

**Issue by kwal2** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#29]
This is not necessarily a problem but needs updating as most BSBI recorders are now using the third edition of Stace's flora.

**Comment by sacrevert** [comment]
Not sure whether to leave this issue open, as is dependent on UKSI, not Indicia.
#3

**Comment by kwal2** [comment]
Just noticed that there are no Lycopods (Isoetes, Selaginella, Lycopopdium, Huperzia, Lycopodiella, etc.)

**Comment by sacrevert** [comment]
I will need to check which uksi groups are enabled. I expect Ginkgo is missing too.

**Comment by sacrevert** [comment]
#28
