### ISSUE TITLE
Develop input system for vascular plants (BSBI)

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#3]
Develop input system as per attached specification

[BSBI online recording interface mockup v4 2016 05 30.docx](https://github.com/BiologicalRecordsCentre/PlantPortal/files/290018/BSBI.online.recording.interface.mockup.v4.2016.05.30.docx)

**Comment by sacrevert** [comment]
Develop input system as per attached specification (update)

[BSBI.online.recording.interface.mockup.v5.2016.10.04.docx](https://github.com/BiologicalRecordsCentre/PlantPortal/files/508669/BSBI.online.recording.interface.mockup.v5.2016.10.04.docx)
@johnvanbreda

**Comment by DavidRoy** [comment]
#26 to be included in list of task.  I'm not sure how to reference to then appear in list above

**Comment by DavidRoy** [comment]
This feels close to be ready for wider promotion. 

I suggest the following key functionality and bug fixes are essential to resolve first, with the rest becoming a future requirement list:
_Priority issues_
GPS precision field #19 
Save to basket functionality #21 (now #64  )
Increase spatial ref flexibility #30
Grid reference precision related #31
Altitude field validation #32
Record list on review tab (3) is corrupted after failed submission #34
Precise gridrefs not saved #37
Vice-county selection #41
Disallow composite 'super-Vicecounties' #43
Should sensitivity be reason rather than precision based? #44
Irish and GB grids are super-imposed #57

Any view on priorites and promotion - @kwal2 @sacrevert

**Comment by sacrevert** [comment]
Seems good to me. #8 and #42 (which you don't list) look to be almost done anyway. I suppose out of the things above perhaps #21 is more of an enhancement (essential part now separated out as #64  , enhancement as #65 )
For promotion I'd be happy to write something for BSBI News (inc. you both and Tom), although I expect a page on the BSBI website would also be good (and would perhaps act as a home for iRecord based support lit. going forwards?)

**Comment by sacrevert** [comment]
I can't remember whether we discussed having a habitat field on this form. David and I were thinking, particularly in relation to status (e.g. planted in/outside of a garden), whether it would be useful to have one level of habitat options available (as per the iRecord general form). @kwal2 @japonicus

**Comment by japonicus** [comment]
I can see that if the form is used generally that there could be a problem with recording in gardens. (BSBI members ought to work on the basis of not recording in gardens - though there's obviously a great deal of ambiguity and scope for interpretation of that guidance).

The habitat categories used for the standard iRecord form are not a good fit if the aim is to distinguish garden v's non-garden.  The applicable category 'Arable land, gardens or parks' seems too broad.

Depending on the target audience, maybe there should either be a clear guidance message on the recording form, e.g. "This should only be used for recording plants in wild situations, plants within gardens should not be included", or alternatively an explicit 'garden' tick-box on the form.  Neither seems a good solution though :confused:

OLP: Now see issue #77

**Comment by sacrevert** [comment]
The iRecord form options are based on EUNIS levels 2 and 3 (or perhaps 1 and 2), anyway, the point is that if we wanted to we could restrict this to a subset, and/or use a finer level. (At the moment 'Arable land, gardens or parks' splits into 'Arable and horticultural' and 'Gardens or parks', but these could be split further if desired). 

Perhaps the habitat option(s) could appear conditionally if someone selected 'Introduced (planted)' etc.?

I think that the guidance message should be used as well though (and a link to the BSBI recording guidelines PDF?)

**Comment by DavidRoy** [comment]
I would favour an appropriate way of recording habitat (adapting EUNIS as Oli suggests) and giving/linking to guidance on how and where to record 'the BSBI way'.

The relevant bit of the EUNIS hierachy for gardens is:
http://eunis.eea.europa.eu/habitats-code-browser.jsp?expand=I,I2,I2.2#level_I2.2

Here is the list of adapted EUNIS terms used on general iRecord input forms.  Can you review - @kwal2
[EUNIS for iRecord_Final.xlsx](https://github.com/BiologicalRecordsCentre/BSBI-Card-and-PlantPortal/files/1340365/EUNIS.for.iRecord_Final.xlsx)

**Comment by kwal2** [comment]
I've commented on the adapted EUNIS terms. Have not spent much time on it but tried to pick main ommissions/weaknesses from a plant recording perspective. Some may be resolved by allowing finer resolution. See what you think.
[EUNIS.for.iRecord_Final (1) KJW comment.xlsx](https://github.com/BiologicalRecordsCentre/BSBI-Card-and-PlantPortal/files/1340483/EUNIS.for.iRecord_Final.1.KJW.comment.xlsx)

**Comment by sacrevert** [comment]
Thanks Kev. It seems then that, in principle at least, you do not object to having an additional, potentially quite long, drop-down habitat field.

Perhaps then there are two tasks:
(i) add a general message of the type Tom suggests (I can create an issue for this).
(ii) think about the best set of EUNIS categories (possibly with finer divisions and/or augmented definitions). I suppose if we do alter definitions, then it should be done in such a way that at a database table is still able to reaggregate them to standard higher categories as appropriate.

Now see issue #78

**Comment by kwal2** [comment]
Agreed. I'm happy to do (ii) and to keep strictly within the confines of broader EUNIS ;-) There may be ommssions which need creating/adding. I've gone through this for NPMS and ALienatt so have a good idea of where the problems lie from a plant's perspective.
