### ISSUE TITLE
Increase spatial ref flexibility

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#30]
Currently the grid ref field is restricted to 1 km or larger scales. Although the form is targeted at lists from 1km or 2km cells, it would be nice if it also allowed for smaller British National Grid areas. 

Also, the error message is confusing to those who don't understand scale/precision. Perhaps once the form allows finer scale grid refs, the error message can just say "please enter a valid grid reference" (if an error is detected).

![image](https://cloud.githubusercontent.com/assets/5985134/20706118/9c1b29b8-b61d-11e6-853f-09c6f13135bf.png)

Nested in #3

**Comment by sacrevert** [comment]
hi @johnvanbreda is this something that is likely to be easy to implement? Or should we downgrade it to a longer term enhancement? I think it would be useful in the longer term to add lists against slightly smaller areas (e.g. 100m squares), but it may not be a priority given some of the other bugs outstanding. @kwal2 @japonicus

**Comment by DavidRoy** [comment]
I think the question is whether you expect recorders to record a list for a 100m grid square, with some finer precision occurrence within the list.  If not, then a version of the standard input form would suffice where you choose a single location for your list - may need being to include additional attributes for plant recording.

**Comment by sacrevert** [comment]
it might be worth encouraging, although possibly the move to apps and real time/location recording gives this kind of enhancement a short shelf-life...?

**Comment by kwal2** [comment]
I would have thought so. I can't think of anyone who has been recorded in 100m grid cells. Might be useful for more NPMS/plot based recording in the future

**Comment by sacrevert** [comment]
OK, fine, then I will close this.
