### ISSUE TITLE
Grid reference precision related

### ISSUE THREAD

**Issue by japonicus** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#31]
After clicking on the map to generate a high precision reference the form does not accept it as is too precise -- ideally map generated refs should be limited to 1km for this form.

Editing the resulting ref to 4-figure still leaves a 10m-related message persisting "Excellent! 10m square selected"

Similarly, use of a 10km square from the map, which is subsequently edited to greater precision still leaves the '10km square selected. Please click on the map again to provide a more accurate location." nag box displayed.

See #3 for umbrella issue.

**Comment by johnvanbreda** [comment]
* Clicking on the map is now limited to 1km resolution.
* Change added to develop branch (for next feature release) to prevent the grid ref hints shown under the map from showing invalid precisions.

Still to do - editing a grid ref should update the help/nag text.

**Comment by johnvanbreda** [comment]
Change added to develop branch for next feature release - editing the grid ref manually removes the help text, since it was really designed to assist when clicking on the map.
