### ISSUE TITLE
Altitude field validation

### ISSUE THREAD

**Issue by japonicus** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#32]
Altitude is not validated at the point of entry.

Altitude values such as 'low' or '10m' are accepted.  At the point of final submission the whole set is rejected with an uninformative message: 'The data could not be saved'.

Returning to the record list does expose validation warnings on the altitude field. These warnings are not cleared even after the altitude field is either blanked or set to a valid value.

See #3 for umbrella issue.

**Comment by sacrevert** [comment]
hi @johnvanbreda would you be able to focus on this next?

**Comment by johnvanbreda** [comment]
Now done.
