### ISSUE TITLE
Vice county displayed using invalid numerical code in iRecord view of record

### ISSUE THREAD

**Issue by japonicus** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#33]
e.g. Oxfordshire appears as Vice-county 732

![screenshot 2016-11-29 10 37 02](https://cloud.githubusercontent.com/assets/207360/20707942/9abf7ff8-b625-11e6-88ff-1bb7e3a8cbf8.png)

**Comment by sacrevert** [comment]
@johnvanbreda it looks like this field has been removed from the view of records received via the BSBI card. Is that in response to this bug report? I think it would be useful to have the record's VC affiliation displayed using the standard names of the vice-counties.

**Comment by johnvanbreda** [comment]
The VC field should be filled in for you as you complete the form, but it seems some forms are being filled in without the vice county value. Do you know how this was achieved (i.e. what browser, and what steps/key strokes & mouse clicks resulted in you getting to the 2nd tab without a Vice County value)?

**Comment by sacrevert** [comment]
I also got this error on records that I was editing earlier e.g. https://www.brc.ac.uk/irecord/record-details?occurrence_id=6003084 but I did select 'Oxfordshire' through the pop-up window (the square overlapped Berks/Oxon), this might also apply to Tom's initial checks as well, because he lives close to the vice-county borders. I am using Windows 7 and Chrome.

**Comment by japonicus** [comment]
The '732' code on the summary in iRecord occurs if I pick a grid-square that intersects a boundary and choose the county(e.g. SU6191 and pick Oxfordshire)
https://www.brc.ac.uk/irecord/record-details?occurrence_id=6003960

If instead I use a non-ambiguous grid-square (SU6090 for Berkshire) then the county is auto-filled on the form but the VC field does not appear at all on the summary in iRecord.
 https://www.brc.ac.uk/irecord/record-details?occurrence_id=6003963

(tested in Chrome 60)

**Comment by johnvanbreda** [comment]
I've fixed it so that all new records will save the vice county field correctly. I've also fixed it so that the name of the VC is displayed rather than the internal location record ID.
