### ISSUE TITLE
Record list on review tab (3) is corrupted after failed submission

### ISSUE THREAD

**Issue by japonicus** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#34]
If the submission of records fails for any reason with a "The data could not be saved" error then the list of occurrences is no-longer shown on the review tab (the records are still visible on tab 2 and can still be submitted)

![screenshot 2016-11-29 10 46 46](https://cloud.githubusercontent.com/assets/207360/20708086/3bd1303a-b626-11e6-9f1e-fd042ff28f9e.png)

See #3 for umbrella issue.

**Comment by sacrevert** [comment]
@johnvanbreda when you are next working on these items, could you prioritise this one please, it seems like the one that might spook recorders the most. Thanks.

**Comment by johnvanbreda** [comment]
Fixed
