### ISSUE TITLE
Recorder name and number of recorders incorrectly marked as invalid

### ISSUE THREAD

**Issue by japonicus** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#35]
Number of recorders and recorder name fields intermittently declared to be invalid (and block record submission), even though they contain valid content.

This occurs when logged in (so the recorder name is pre-populated).  It may be only after a batch of records has already been sent - not sure, as problem appears intermittently.

Re-entering the two fields (even with identical values) clears the error and allows submission.

![screenshot 2016-11-29 10 45 07](https://cloud.githubusercontent.com/assets/207360/20708230/f8d78044-b626-11e6-9520-0b4a91a6a48a.png)

See #3 for umbrella issue.

**Comment by johnvanbreda** [comment]
Fixed.
