### ISSUE TITLE
SmpAttr 992 and 127 missing (number of recorders and recorder name) missing on edit

### ISSUE THREAD

**Issue by japonicus** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#36]
Editing an existing record (without changing number of recorders or recorder name) results in SmpAttr 992 and SmpAttr 127 missing errors after attempted (failed) record submission.

![screenshot 2016-11-29 10 51 38](https://cloud.githubusercontent.com/assets/207360/20708370/75f227c8-b627-11e6-9645-cffe986e9264.png)

possibly related to #35
See #3 for umbrella issue.

**Comment by johnvanbreda** [comment]
Fixed.
