### ISSUE TITLE
Precise gridrefs not saved

### ISSUE THREAD

**Issue by japonicus** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#37]
Precise grid-references are not saved.  I have yet to manage to submit one correctly, but am not absolutely sure whether the precise refs are lost during first submission or after re-submission following an error.

e.g. occurrence id 4333333 should have a precise grid ref of SU616919

Screen shot showing correct settings prior to submission:

![screenshot 2016-11-29 11 08 57](https://cloud.githubusercontent.com/assets/207360/20708542/4e87f1e4-b628-11e6-9235-36ee515cece7.png)

See #3 for umbrella issue.

**Comment by sacrevert** [comment]
@johnvanbreda Hi John, just wondering if there was progress made on this, and whether it should be closed. Thanks

**Comment by johnvanbreda** [comment]
Yes, I believe this to be working correctly now.
