### ISSUE TITLE
Map highlights 'ghost' precise locations that are not set

### ISSUE THREAD

**Issue by japonicus** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#38]
There is a conflict between placename linked 'saved' site gridreferences and the used reference shown on the summary map.

Steps to repeat:
Selected a saved placename, e.g. Benson is linked to SU616918 for my account
Gridref is not filled automatically
Enter a 4-fig gridref
Enter a record on tab two, _without a precise gridref_
Summary tab three marks the position of the precise square (SU616918) from step one, even though no record uses that.

(on screenshot yellow shading correctly represents SU6191, red square is spurious 100m square not used by any record)

![screenshot 2016-11-29 11 48 56](https://cloud.githubusercontent.com/assets/207360/20708865/daab0b56-b629-11e6-9fca-a93aacfffb0e.png)

See #3 for umbrella issue.

**Comment by johnvanbreda** [comment]
I'm not 100% sure I agree this is spurious. In this case, the records will be linked via the parent sample to the Benson location record. If you have chosen a site in the Location field to link your records to, then it makes sense to show the boundary of the site on the review I think, even if you've added a larger 1km square. If you didn't mean to link the records to the Benson site then perhaps it would make more sense to search for Benson in the "search for a place on the map" control?

I would agree that changing the colour or appearance of the site boundary outline to not clash with the finer grid reference records might be a good idea, e.g. making it blue. Let me know if you agree.

**Comment by japonicus** [comment]
I think this issue is not hugely import, so is probably not worth spending much time on.

I'm unsure how the relationship between saved sites and associated records (that have their own independent grid-reference) works. E.g. it appears that it would be possible to associated my 'Benson' saved locality (SU616918) with a record from an incompatible grid-square (e.g. SU6190).  I don't know if that matters, but I think it is something that a real user might do innocently.

I'd assumed that in this situation 'Benson' would be saved as just a text string, rather than tying the recording card to the existing entity that has its own associated (and different) geo-reference.

My precise saved location is a centroid on my garden, it would be easy to inadvertently use it for records for the whole village. There's scope for confusion as the recording form has two different fields where one can type in a place name.

**Comment by johnvanbreda** [comment]
Samples have a location_id foreign key pointing to the saved sites which is optional. There is also a free text samples.location_name field. When you enter a location name it searches your saved sites and if you pick one, then the samples.location_id is filled in, otherwise the entered text is filled into samples.location_name as free text. You were expecting the latter but got the former. 

It is indeed possible for a record to exist outside it's linked site but it is equally possible for a form to be coded to validate against this. As the site boundary is not implicitly stored against the record, the way we are using the location just acts as a handy prompt for verifiers - if you'd linked a record in another village to a site named Benson then it would raise concerns. Your case is slightly odd I suppose in that you've named your garden "Benson" rather than "A garden in Benson".

**Comment by sacrevert** [comment]
As far as I can see it sounds as though this should not create problems in terms of actually associating erroneous grid references with occurrences directly, as long as all syncs/downloads etc. understand how the association between saved sites and actual record geo-references works.

Would a good solution, then, be to change the colour of the site geo-reference on the Review tab as John suggests, but also to provide some explanatory text relating to the function of saved sites, and possibly a link to some guidance (if some exists)? @johnvanbreda @japonicus @kitenetter

**Comment by johnvanbreda** [comment]
I'll await confirmation before changing anything. The guidance could presumably be generic as the issues are similar when using the normal recording forms?

**Comment by sacrevert** [comment]
yes, exactly. @kitenetter and @DavidRoy are best placed to tell us what might already exist and where.

**Comment by kitenetter** [comment]
I'm not aware of any existing guidance on how iRecord handles location names/My Sites etc., and I agree that it would be useful both for this plants form and more generally. I will draft something when I can.

**Comment by sacrevert** [comment]
Location field no longer shown on overview map, closing
