### ISSUE TITLE
Support for Irish Grid-references

### ISSUE THREAD

**Issue by japonicus** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#40]
The grid-reference field rejects Irish grid-refs - these should be allowed.

See #3 for umbrella issue.

**Comment by johnvanbreda** [comment]
Irish grid option now enabled.

**Comment by sacrevert** [comment]
Is it easy/possible to have the irish grid appear when 'irish grid' is selected. currently the British grid remains, overlapping Ireland.

**Comment by johnvanbreda** [comment]
I think this is 1-2 days work as it requires new code.

**Comment by DavidRoy** [comment]
ok, let's leave this for the time being

**Comment by sacrevert** [comment]
Shall I move to the iRecord issue tracker @DavidRoy ?

**Comment by DavidRoy** [comment]
Yes, good idea
