### ISSUE TITLE
Precision of surveying time field [vague dates in user profiles]

### ISSUE THREAD

**Issue by japonicus** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#42]
Although nice to have, should the 'Time surveying' ~~field be required and, if required,~~ need such precision?

I suspect that many recorders might be hard-pressed to fill this in accurately and if 'required' will give a false answer (which is worse than no information).

The surveying period is capped at 24h which rules out the use of this form for records from >1 day.  (similarly the date field is constrained to day precision) Although we want single-day precision, that's not necessarily compatible with how people currently record, and would also prevent the use of this form for digitisation of old recording cards (often at month or year precision). 

See #3 for umbrella issue.

**Comment by sacrevert** [comment]
'Time surveying' is not currently mandatory -- are you asking whether it should be? Agreed that half-hourly precision would be sufficient, although this presumably means a drop-down menu would be best?

Surveying is capped at one day, the thinking was that historic data would be (eventually) via a separate form (#11). However, people clearly do still collect data for a grid cell over longer periods, and there is an option to allow the manual entry of vague date ranges. Perhaps you (@japonicus)  and @kwal2 can decide whether you want this enabled. The only issue then is that pop-out guidance on accepted vague date formats might be required?

**Comment by japonicus** [comment]
Sorry, yes you're right.  I think having experimented with various invalid values I got confused, as they were blocking form submission. I don't think it should be mandatory - so that part of the form is fine :)

Less fine-grained precision on the survey time field might be useful.

Personally, I'd prefer that multi-day ranges be allowed, but discouraged. 

As I understand it #11 is related to herbarium specimens and literature reports, whereas I was thinking more of old recording cards that some people are still digitising.

**Comment by sacrevert** [comment]
So @johnvanbreda to implement restricted (half hourly) survey times

@kwal2 to comment on whether to allow vague date ranges on this form. 

You are right that #11 was imagined as being intended for herb/lit reports, but it could be extended to deal with vague dates. Personally I think this would be a good opportunity to reduce the practice of vague dates, but @japonicus has a much better idea of the numbers of people doing this, and so whether it would have a large impact on usage of the form. @japonicus  and @kwal2 to discuss

**Comment by japonicus** [comment]
For current recording, precision looks to be a non-issue (~ 99% of recent records use precise days).  To me it just seems odd to limit the use of the form to exclude capture of old recording cards (which often lack precise dates). Old recording cards would otherwise a good fit for this data-entry form, whereas I imagine the forms envisaged for #11 would be much more complex.

![Date precision in the DDb 2000-onwards](https://cloud.githubusercontent.com/assets/207360/20715348/c5c63860-b646-11e6-96be-e381f523c6c4.png)

**Comment by sacrevert** [comment]
OK, thanks Tom, I assumed it would be lower and therefore an increased need to persuade people to shift to day precision. Reversing a previous decision then, can @johnvanbreda enable vague dates, and perhaps include a link to the Recorder 3 page (or other) outlining the accepted formats?

**Comment by japonicus** [comment]
I've just realised that my precision table above slightly mis-represents things, as the year grouping on the rows implicitly excluded date ranges that spanned multiple years.  That will understate records with only dateclass-level accuracy - but I wouldn't expect any future recording to be so imprecise.

At the risk of adding rarely used complexity, we could insist that dates from 2017 onwards have day-level precision if entered using this form (i.e. fail validation of date range records recorded after 2016).

**Comment by sacrevert** [comment]
Speaking naively, that seems even more complex to me (at least in terms of the user interaction). I don't mind either way, but I would probably be happier with one or the other, and, if we go with allowing vague dates, a message stating that day-resolved data are preferred. if @kwal2 can make the final decision, that would be fine with me.

**Comment by kwal2** [comment]
Not sure I've followed the detail but there seem to be two separate issues here:

Time surveying - not mandatory and I would be happy with to 30 min accuracy. This is really to help in analyses to determine recorder effort. I can't imagine this needing to be more than 24 hour.

Date ranges - I think we need to allow vague date ranges; certainly to month and year precision as I can imagine recorders using this for digitising data from others who might not have specified day of recording (but as Tom says this is rare these days).

**Comment by DavidRoy** [comment]
Just catching up with this.  I'm of the view to not implement vague date functionality, because it complicates the user interface (i.e. we loose the simple date picker) for a narrow and diminishing requirement.  I favour creating a cloned version of the form for this purpose and giving a message on the main form along the lines of 'if you want to submit records with a vague date (i.e. that span days, months, years etc) please use **this** version of the form'.  The same goes for other rarely used complexity.

**Comment by johnvanbreda** [comment]
Vague dates - are you aware that there is a possibility to configure Indicia to allow vague dates to be turned on as an option in the user profile? Then all forms would show a vague date compatible input box not just the Plant Portal one.
Times - if I set up a range of possibilities in a drop down, e.g. 0:30, 1:00, 1:30 etc, then how will we encourage the user to be consistent with the way they interpret times in between the half hourly intervals? Or should I set the time values up as a range, e.g. 
<30 mins
30 - 59 mins
1hr - 1h29mins
etc?
Or, just have a hint underneath "Please select the nearest time available"?

**Comment by DavidRoy** [comment]
Thanks for the reminder about the vague date option.  I think this is a good option.  How much effort to implement?  Can the plant input form then give a message to say something like 'if you want to submit records with a vague date, please click here to set this option in your account setting.'

On times, one for @kwal2 to decide but I like the idea of a drop-down list as it's more useful (for modelling etc) to have fixed categories

**Comment by kwal2** [comment]
Happy with a drop down giving 30 min intervals. I doubt folks would want to be more precise than that.

**Comment by DavidRoy** [comment]
Thanks.  What's the maximum or shall we have a final category of 7+ hours?

**Comment by kwal2** [comment]
Most of my Scottish recording days are 7+ ;-) Any reason why we can't go to 10+?

**Comment by DavidRoy** [comment]
To cover the hard-core, the categories are then:

![image](https://cloud.githubusercontent.com/assets/2699478/21180585/a41a9024-c1f1-11e6-96f9-c6747d83770d.png)

**Comment by johnvanbreda** [comment]
Categories done for time surveying. 

Enabling the account settings is theoretically only about an hour's work, if it all goes to plan. It's not very well tested code though so there is a risk it will need debugging. Shall I give it a try?

**Comment by DavidRoy** [comment]
Thanks for implementing categories.

If you implement the account settings and a user chooses to enable vague dates, would this then apply to all recording forms for that user?  And if so, does the user loose the date picker in date controls?

**Comment by sacrevert** [comment]
@johnvanbreda I assume this issue can be closed? I'm not sure where you got to regarding implementing this and answering @DavidRoy 's questions, but it looks to me like it could be closed.

**Comment by johnvanbreda** [comment]
> If you implement the account settings and a user chooses to enable vague dates, would this then apply to all recording forms for that user? And if so, does the user loose the date picker in date controls?

Yes, it would mean that a user which chooses the vague dates option in their account profile will get vague date enabled date controls everywhere. When enabled the date picker still works but you would click a calendar icon next to the input to invoke it, rather than it automatically appearing when you click in the box.

@DavidRoy Shall I enable the option to switch vague date entry on in the user account profile?

**Comment by DavidRoy** [comment]
@johnvanbreda, yes please implement with the default is that users have vague date entry OFF

**Comment by sacrevert** [comment]
@johnvanbreda could you confirm when this is done? Thanks.

**Comment by johnvanbreda** [comment]
@sacrevert This is now done
