### ISSUE TITLE
Disallow composite 'super-Vicecounties'

### ISSUE THREAD

**Issue by japonicus** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#43]
It's possible to enter multi-VC entities such as 'Sussex' or 'Yorkshire' as the county.

Under some circumstances these can also appear on the county suggestion list after clicking on the map. E.g. zoom out from York and click and the suggested counties list gives:

'North-east Yorkshire'
'Yorkshire'

Nested in #3

**Comment by kitenetter** [comment]
Agree that aggregate or other non-standard VCs should be disallowed. Having entered a random grid ref "SU8614" into the iRecord form I got asked if it was in VC West Sussex or in (non-VC) Sussex, which seems unhelpful:

![image](https://cloud.githubusercontent.com/assets/16039111/25231219/f722fc7a-25ce-11e7-9be6-caa1d8576a9c.png)

**Comment by sacrevert** [comment]
@johnvanbreda Is this one to be altered with any impending code updates? The example given by Martin above still seems to exist.

**Comment by johnvanbreda** [comment]
Yes, this is fixed in the code pending the next feature update.
