### ISSUE TITLE
Should sensitivity be reason rather than precision based?

### ISSUE THREAD

**Issue by japonicus** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#44]
...adding issue/feature request from earlier email discussion.

"If sensitivity is recorded on the form then I don't think this should be expressed as a level of precision-blurring - because that severely ties our hands in terms of how data can eventually be used, released or licensed. If we need 'sensitivity' at all then I think it should be expressed as 'sensitive'/'not-sensitive' i.e. a tick box (or perhaps as a categorised field specifying the reason for sensitivity e.g. 'vulnerable taxon' 'private land' etc.)  That leaves more scope for future re-interpretation of how data can be released."

If the current precision-based criteria are retained then I think the options should be cut back so that only blurring up to 2km can ever be requested (currently goes up to 100km!).

see #3 for umbrella issue.

**Comment by johnvanbreda** [comment]
@sacrevert @DavidRoy what are your opinions on this proposal? We could potentially just have a tickbox for sensitive and use this to set precision to 2km if ticked. Then we'd know (for this dataset at least) that the user had not specified the blur, therefore would be less tied down in how it is interpreted when using the dataset.

**Comment by DavidRoy** [comment]
I'm happy with that proposal

**Comment by sacrevert** [comment]
Me too.

**Comment by johnvanbreda** [comment]
Done - sensitivity now a checkbox which sets the blur to 2km.
