### ISSUE TITLE
Linking iRecord App

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#50]
There is a requirement to link the iRecord App to the vascular plant recording form on iRecord. The idea behind it is that the app would be able to enter records of plants in a grid-mode (atlas-mode). Those records submitted this way would result in the vascular plant survey sharing the same editing form on the iRecord website.

A common scenario would be: 
1.  User toggles the grid-mode
2. (optional) Selects the resolution of the grid square in the app settings
3. Start recording species within the GPS located square
4. (optional) Add survey level attributes like number of recorders, time surveyed
5. Send that record

If the user moves to another square while recording species, the app will warn the user and the new species recorded will be automatically added to a new survey with a different square. So in reality, the user would not have to care about finishing recording in one square before moving to another as this would be automated in the background.

I hope this is OK with everyone.

Nested in #3

**Comment by johnvanbreda** [comment]
Ok with me. We need to make sure you submit against the correct sample.input_form and sample.survey_id and use the same attribute IDs.
Is there a requirement to support specific record-level grid references for interesting records as you can in the form, i.e. you enter a list of records in the 1km grid square but for any records that are interesting in the square you can provide a one off grid reference for the record (with a sub-sample in the submission).

**Comment by sacrevert** [comment]
My understanding was that all records will have precise (phone) GPS references through the app, with the selected square (at whatever scale) merely serving as a sample level grouping variable, but it will be interesting to see whether I have this right and Karolis affirms this : )

**Comment by kazlauskis** [comment]
Hi John, yes, I think this will be done by default. Every subsample will have a location set automatically by GPS or the user.

**Comment by kazlauskis** [comment]
Hi @johnvanbreda, I have this issue (copied here from our email conversation).

I got a bit stuck with the spatialref attribute. I cannot find a way to submit a sample with a finer-located subsample that would render correctly on the vascular plant form. 

If I send such a simplified model of a survey level sample with a single child subsample and occurrence
```json
"sample": {
  "fields": {
    ...
    "entered_sref": "NY1010",
    "entered_sref_system": "OSGB",
    "sample_method_id": 7305
  },

  "samples": [{
    "fields": {
      ...
      "entered_sref": "NY101101",
      "entered_sref_system": "OSGB",
      "sample_method_id": 7305
    },
    "occurrences": [{
      "fields": {
        ...
        "taxa_taxon_list_id": 11212,
      }
    }]
  }]
}
```

instead of:
```json
"sample": {
  "entered_sref": "NY11",
  "occurrence": {
    "spatialref": "NY1212",
  }
}
```

Then I see the vascular plant form showing the survey level gridref as my submitted subsample (NY101101) and the gridded species list does not have any finer gridrefs.

If I included spatialref attribute within the occurrence model that would probably create an even another subsample, no?

I wonder how I can submit such a model that would render correctly in the form?

Thanks!

**Comment by johnvanbreda** [comment]
Looking at the database, it appears the sample/subsample hierarchy is not being created properly, None of the recent samples in this survey have their parent_id set although I can see you've been submitting samples in pairs which look like they should be linked. So maybe your code for the "samples" json entry is not behaving correctly?
Also note that the sample_method_id=7305 only needs to be set on the first parent sample, not the subsample.

**Comment by kazlauskis** [comment]
Thanks @johnvanbreda, using **fkID='parent_id'** instead of **fkID='sample_id'** for child samples has solved the issue.

**Comment by sacrevert** [comment]
@kazlauskis @johnvanbreda Can this issue be closed now?

**Comment by johnvanbreda** [comment]
That probably needs @kazlauskis or someone using the app to confirm.

**Comment by kazlauskis** [comment]
Thanks, I will check this up this weekend.

**Comment by sacrevert** [comment]
hi @kazlauskis did you come to a conclusion re this?

**Comment by kazlauskis** [comment]
I think this is the question for @DavidRoy to answer as he is the person that receives the feedback for this functionality. From my perspective, I think, it could be closed.

**Comment by DavidRoy** [comment]
Ok to close this issue and open new ones if any bugs emerge
