### ISSUE TITLE
Status and Stage should default to blank rather than repeating previous entry

### ISSUE THREAD

**Issue by japonicus** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#53]
The occurrences form correctly defaults to a blank status column, but newly added rows then acquire the previously used value automatically rather than staying blank.

Recorders may overlook or ignore this, which I think this is likely to lead to a tendency to mis-apply status.

The same problem also applies to the Stage column, which should also default to blank for each entry.

related to #51

**Comment by johnvanbreda** [comment]
@sacrevert do you agree?

**Comment by sacrevert** [comment]
Yes, certainly. Thanks Tom!

**Comment by johnvanbreda** [comment]
No problem - done.
