### ISSUE TITLE
Vascular plant form species filter allows option for non-plant groups

### ISSUE THREAD

**Issue by japonicus** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#54]
Clicking the filter icon on the 'species' heading of the occurrence form opens a dialogue box that allows the input form to be modified to accept non-plants.  In the context of a plant recording form this seems nonsensical. It could tempt recorders to add additional taxon groups.  That could create data-flow problems and would also cause the spurious observations to have an inappropriate set of status/stage etc. attributes applied to them.

![screenshot 2017-04-23 11 24 07](https://cloud.githubusercontent.com/assets/207360/25312724/3bd3b706-2818-11e7-9669-912ea97dd30a.png)

**Comment by johnvanbreda** [comment]
Agreed - I've removed this option.

**Comment by japonicus** [comment]
thanks :)
