### ISSUE TITLE
Sensitivity requirements

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#6]
I could not see any mention of sensitivity in the scoping document. What are the requirements for this and plant portal?

Is the assumption if there is any sensitive data then people in a group would have rights to see it at full precision?
If not, then things could become complicated.

Even then, we need to make sure we are careful about who can assign rights to the groups if there is sensitive data involved

**Comment by sacrevert** [comment]
I don't think that there will be any issues with sensitivity for the historical data that we hold. Whether or not we want to allow users to mark samples as sensitive (and degrade the precision of viewing and download), I don't know. I would be inclined to insist on openness for all datasets uploaded (that is, a Creative Commons license must be chosen). I'm not sure about what @DavidRoy thinks. It might be desirable to have some sort of embargo period option for consultancy data, although if you tell me that this is a lot of extra work then I would not be too concerned about putting it on a long list of potential future enhancements (funding permitting).

**Comment by DavidRoy** [comment]
I agree with Oli.  Not an immediate requirement

**Comment by andrewvanbreda** [comment]
I am not sure what your thoughts on what an embargo period would involve, so it is difficult for me to say if it is much work.

**Comment by sacrevert** [comment]
Well, probably the ability to degrade species occurrences within a set of samples to 10 x 10 km, both for viewing and download.

**Comment by DavidRoy** [comment]
I do not think this requirement is needed at this stage.  I suggest we build on the premise of fitting within CC licence frameworks to start with
