### ISSUE TITLE
System to set Plant Portal Spatial Reference Type attribute automatically

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#61]
If a Vice County or Country is used to generate the spatial reference then the Plant Portal Spatial Reference Type should be automatically set to boundary

**Comment by andrewvanbreda** [comment]
@sacrevert can you let me know if this change is to go ahead or to be put on hold for further funds to be made available?

**Comment by sacrevert** [comment]
I think we can shelve it, awaiting further funds. The initial data loading will all be done by me, so I can use the manual mapping that you have created.

**Comment by andrewvanbreda** [comment]
Now coded (on my own machine) and committed, not on dev yet.

- Spatial reference type now hidden from mappings screen.
- Spatial reference type now sets to “gridded” or “boundary” automatically

A couple of other improvements whilst I was at it:
- Results can now be scrolled horizontally if there are many columns on the warning screen.
- Fixed bug which stopped the spatial reference often failing to be set from the Vice County or Country (due to a missing trim of white space during a comparison)

**Comment by andrewvanbreda** [comment]
Sorry I just realised you had said not to go ahead with this enhancement. It didn't take too long in the end anyway
