### ISSUE TITLE
PP sample/plot logic clarification

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#71]
**AvB:** Some rows wth same sample id are split up in the file so they aren't on consecutive rows

**OLP:** I did that on purpose, thinking what the average user might do. Now I am thinking whether the checks need to be more intelligent. For example, here, the occurrences with the same sample id that are not on consective rows are actually for different plots, so, should the importer realise that they cannot actually be the same sample?

**OLP:** Does the current logic mean that a user can use the same sample IDs for different plots, but only if they are uploaded in separate tranches?

**AvB:** It also found rows with the same sample id but different spatial references

**OLP:** I suppose this is the same issue as above. The warning is correct, but if the importer checked the plot it would know that they were not the same sample (and that that the different spatial refs were allowed).

**OLP:** If you can answer the question above, then I suppose I can explain this in the guidance (particularly if fixing this logic in the importer is a biggish job).

**AVB Response:** Hi Oli, What you are describing is what the standard Indicia importer used to do. However, (I thought) the point of the Unique Spatial Reference ID was to have an exact way of determining the sample the different occurrences would go into. So the above behaviour is very deliberate.
The user would know exactly that rows with the same sample ID would go into that sample and there wouldn't be any complications of sometimes it would do this, sometimes it would do that, based on a series of rules.
It would simple be based on the Unique Sample ID (and obviously the rows would have to be have consistent dates etc). They need to be on consecutive rows just to make the programming easier.
The idea was that the user would know exactly that the occurrences would going into the sample with that ID, unless there was an inconsistency flagged.
Once the importer is done, the Unique Sample ID wouldn't really be used.
Let me know if I have that totally wrong

Nested in #46. Arising from #68

**Comment by sacrevert** [comment]
OK. I can see where we are both coming from here. @andrewvanbreda 

You are saying that the 'unique sample ID' is only for distinguishing samples _within an upload_ whilst I (and my test file) was working from the position that the sample ID could potentially have some meaning in relation to the user's own sample labelling.

I think that the way that you have understood it is fine. I will just have to make sure that I describe it in the guidance accurately. Users will obviously have custom plot names, dates and spatial refs to inform them about where and when the sample was collected anyway, so, allowing users to use 'informative' sample IDs is probably overkill anyway.

If you agree with my summary and conclusion above, then perhaps you can comment and close the issue.

**Comment by andrewvanbreda** [comment]
Well it is possible to have it so that it has some meaning by forcing uniqueness or making the user aware of whats always in the database so they can choose an appropriate ID, but then it could only be made unique for their own data because otherwise we would have to show them other people's data.
I can see this being a bit chaotic.

However, then intention of the sample external_key field is probably not just to discard it, or leave it in the database in a meaningless way
I think you are right to aim to close this issue, but I would just like to think about this a little bit longer.
It may be that we use the field during import, but then actually clear it so it doesn't get saved at all to the database

**Comment by sacrevert** [comment]
>Well it is possible to have it so that it has some meaning by forcing uniqueness or making the user aware of whats always in the database so they can choose an appropriate ID, but then it could only be made unique for their own data because otherwise we would have to show them other people's data.
I can see this being a bit chaotic.

Yes, agreed.

>However, then intention of the sample external_key field is probably not just to discard it, or leave it in the database in a meaningless way
>I think you are right to aim to close this issue, but I would just like to think about this a little bit longer.
It may be that we use the field during import, but then actually clear it so it doesn't get saved at all to the database

Yes, I don't think it is wise to discard it if we are asking the user to create it (and therefore to give it some thought). I think storing it in the db is sensible. Of course, the guidance will have to explain its purpose in the upload, but if the user understands its function in the upload/database, then they can decide how they want to use it (e.g. a user who wanted to maintain some set of sample labels that they had recorded in the field, but which overlapped [e.g. plot 1 had samples 1-10, but plot 2 also had samples 1-10], then they might decide that they wanted to upload the two sets of samples separately in order to preserve their labelling).

**Comment by andrewvanbreda** [comment]
OK, I think my only concern left is that would don't confuse anyone else who is using the sample external key on the warehouse, but I suppose we would have to assume that any external keys that happen match for anther survey/website are not going to be relevant to them and presumably they wouldn't be querying the database directly
I happy to close this now if you are Ok with this?

**Comment by sacrevert** [comment]
There will presumably be some sample external key matches between users (e.g. where just series of numbers are used), but, I presume from what you say above about "they wouldn't be querying the database directly" that you are implying that they would only be using reporting tools that we have created. If that is the case, then I agree, and am happy for you to go ahead and close this issue.

**Comment by andrewvanbreda** [comment]
I was just thinking aloud that the users wouldn't have any of the worries I might have querying the database and need to worry about getting the data only for specific projects even if the external key matches. As you say they will be using reporting tools so that will be done for them
