### ISSUE TITLE
Plot data importer not working with CSV files containing only one sample (not one row, will still fail with multiple occs)

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#76]
I am going to leave this for now, but I noticed the importer doesn't work if only 1 data row is specified (so two rows if you include the header). Probably needs fixing before final live, but not before David/Oli start populating DB with data

**Comment by andrewvanbreda** [comment]
Raising priority of this and also changing title as issue is not what I thought.
There is a bug importer where if the CSV contains file header names that EXACTLY match the ones I am using for auto generated columns, then the importer gets confused.
For instance, if the user specifies EXACTLY "Spatial reference system" in their file then the code gets confused as this is the header name I automatically add when the user specifies a general spatial reference system.

It actually even goes wrong if the column isn't mapped.

Although perhaps not the most elegant solution, for now I might change the column headers I am auto-generating to use names the user definitely wouldn't specify. I am assuming that works as a fix of course, not tried yet.

**Comment by andrewvanbreda** [comment]
Above issue was fixed and committed by just changing my auto-generated column headers to ones user almost certainly won't use, my now include "(auto-generated)" in the name.

However there appears to still be an issue, and actually it goes back to when I originally raised this issue saying it didn't seem to work if there was only one data row. I then thought this isn't what was happening, indeed I was correct, however there is still an outstanding similar bug. The import fails if there is only one sample created, this is slightly different as there could be multiple occurrence rows.
I don't think it is worth explicitly trying to fix this anymore for now as I can see myself grappling away at it for a long time and not getting anywhere. Best let it simmer in the background and hopefully I will get a light bulb moment

**Comment by sacrevert** [comment]
OK, fine, shouldn't be important for my data loading anyway (particularly if I know to avoid the scenario)
