### ISSUE TITLE
recording form guidance message

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#77]
@kwal2 @japonicus @DavidRoy @sacrevert

We have decided that a guidance message would be useful on the BSBI form. If it could be immediately below the "Enter a vascular plant record card" text, then it would appear above all of the data entry/review tabs.

My suggestion for the text is:
"This card has been designed for recording plants according to the BSBI guidelines. Species that are planted in gardens should in general not be recorded. Please see this [document](http://bsbi.org/download/4815/) for more detail on the recommended approach."

I suspect the document may move BSBI URL in the future, so it might be worth while hosting this locally on one of the CEH servers?

Nested in #3

**Comment by johnvanbreda** [comment]
Done. If the document is placed on a CEH server then let me know and I can change the link.
