### ISSUE TITLE
Enable Channel Islands UTM grid

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#79]
Enable Channel Islands UTM grid in the spatial reference drop down menu (and display grid on map)

Nested in #3

**Comment by johnvanbreda** [comment]
Can you confirm the format please - should this be the WA/WV format military grid, or just an easting northing? I've recently had dealings with Jersey where they've expected the latter rather than the former.

**Comment by japonicus** [comment]
In the context of gridsquare-based botanical recording it should be WA/WV because easting/northing co-ordinates would denote an absolute point rather than a square.

**Comment by johnvanbreda** [comment]
Ok - thanks, that's done.

**Comment by sacrevert** [comment]
The WA/WV (UTM) based system is of course traditional, but the Jersey recorders use a government app that saves and exports records in lat/long. So, if we do eventually allow for recorders to upload spreadsheets of records to this system, we might need to allow for lat/longs in Jersey (and convert them to UTM grid squares). I'm not suggesting reopening this, it is just a reminder for myself.
