### ISSUE TITLE
Vascular plant card multiple recorder names

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#8]
From the spec:
It would also be useful to enforce separate boxes for multiple recorder names (i.e. provide a ‘+’ option add as many additional boxes as there are recorders). This would be much better for enforcing the separation of names, which is highly desirable for BSBI DDb data exchange.

See #3 for umbrella issue.

**Comment by johnvanbreda** [comment]
This can be implemented after the next feature update to iRecord. Requires a multi-value attribute with @control_type=complex_attr_grid and with the @encoding option set to disable storing the values as json.

**Comment by sacrevert** [comment]
I'm just wondering whether we have had the 'next feature update', and whether this can be closed. Or perhaps it should be left open until the actual interface for inputting multiple names is enabled?

**Comment by johnvanbreda** [comment]
This has now been deployed and is ready for you to check.

**Comment by sacrevert** [comment]
Thanks John. I will have a look. Also flagging @japonicus in case there are other technical data exchange issues that need consideration.

**Comment by sacrevert** [comment]
Looks good to me, although perhaps we could add a message stating:
"Please us the following format for names: Albert N. Other. If there are a number of recorders, lists can be truncated to those leading the group, but 'Number of recorders' should indicate the true size."

**Comment by japonicus** [comment]
Looks good.
 I noticed that the ordering of multiple names is unstable if a record is edited. e.g. I entered a record with two recorders "Tom Humphrey" and "A.N. Other". The record initially appeared in search results under "Tom Humphrey", the record page listed both recorders in the order entered.

When I re-displayed the edit view of the record the order of recorder names had reversed.  After saving A.N. Other was listed as the first recorder.

Repeating the edit put "Tom Humphrey" back.

**Comment by japonicus** [comment]
Currently, the summary view of records with multiple names displays only the first of the names, would it be possible to display the full list (or to indicate that there are multiple records, e.g. append an ellipsis suffix).

The detailed view of records has both a 'Recorder' attribute and one or more 'Recorder names' which is confusing. Only 'Recorder names' should be displayed.

Exported records only display the single 'Recorder' rather than the full set of multiple names.

**Comment by japonicus** [comment]
The edit form isn't escaping quotes correctly resulting in truncated names (and potential html-injection vulnerabilities) e.g.
'A. "Bert" Other' is truncated to 'A. ' when the record is next edited.

A more minor issue is that names are also truncated at semi-colon when edited, e.g.
'A. N. Other; Foo Bar' becomes 'A. N. Other' after editing.

**Comment by japonicus** [comment]
Deleting names doesn't work. Clicking the delete button shows the name greyed and struck-through but, after saving the record, the deleted name is still present.

**Comment by sacrevert** [comment]
@johnvanbreda @DavidRoy Hi John, just wondering whether you have the resources to deal with these issues raised by Tom (and my text edit). It seems like these are important things to iron out before we launch this page to BSBI recorders. Thanks.

**Comment by japonicus** [comment]
Of the issues raised here I think the most significant is that deleting names doesn't work.  

Problems with quoting and semi-colons affect several Indicia forms and probably eventually need a more general fix applied to escaping of output (maybe that is already fixed, I haven't re-tested recently).

**Comment by johnvanbreda** [comment]
@sacrevert Yes, I can get onto this in the next day or two.

**Comment by johnvanbreda** [comment]
All issues now fixed.
