### ISSUE TITLE
Survey summary enhancement

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#81]
It would be nice if, on the "Review and submit" tab, a count of the number of taxa entered appeared (I suppose we could further enhance these summary options using data from iRecord in the future, e.g. number of species recorded by others in the same monad/hectad/whatever etc etc).

**Comment by johnvanbreda** [comment]
Fixed in develop branch so will be updated at next feature release.
