### ISSUE TITLE
Editing submitted 'cards'

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#82]
At the moment there is no way to edit cards, besides entering the card by editing an from individual record.  A list of samples would be useful. I suppose this links to the enhancement in #64 but simply providing a list of submitted samples might be easier than the requirement in #64 to deal with unsubmitted forms as well. 
I think this is an important enhancement. 

Nested in #3

**Comment by johnvanbreda** [comment]
I agree with this suggestion. @DavidRoy I wonder if this is a general requirement though - should there be a "My samples" added to the Explore menu (or perhaps "my form submissions" or something more user friendly). 
We could then add a flag to the vascular plants form called "in progress" and withhold in progress records from reports and verification, then display this flag on the my samples list. The my samples list could also display a count of records + count of verified records.

**Comment by DavidRoy** [comment]
I agree that this is a general requirement and could usefully be either:
- a new report under the Explore menu
- a new tab under the Explore-my records report.  This report is effectively a 'my occurrences' report. 
 All occurrences belong to a sample, although some samples (rare instance) can lack occurrences. 

Probably a separate report is clearest to users, and allows more flexibility.  I agree with the additional (hyperlinked) fields of count of occurrences and count of verified occurrences (maybe also count by all record_statuses to include queried or rejected records)
