### ISSUE TITLE
Fine-scale grid ref info lost on edits

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#83]
If fine-scale information is added for a plant, but then the card is edited (going in via a record through 'My records') by adding an additional fine-scale record at an existing grid ref, or by altering an existing record to be more fine scale by using an existing fine-scale grid ref, then the fine-scale record detail is not saved. I think this also applies if a new record with the same fine-scale record as an existing record is added to the card (this actually appears to result in existing fine-scale records being deleted).

These things appear not to apply if the added fine-scale information is different to existing information. So, there is some interference between records with identical fine-scale grid ref information on editing.

Although I have reproduced this, originally it occurred with genuine records for Setaria pumila and Stachys arvensis at SU684887. (It would be good if these could be undeleted in the database, or I can add them again when the bug is fixed).

**Comment by johnvanbreda** [comment]
Fixed.
