### ISSUE TITLE
Get Plant Portal dev site importer running

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#87]
The importer on the Plant Portal dev site site needs to be setup

Currently tasks are
1. Update the Warehouse Plant Portal Module config file on the Dev Warehouse.
This file has been sent to BRC sys admin by email.
(I believe this Warehouse is currently running the dev branch, this branch has got the Plant Portal importer change merged into it with the exception of the changes that relate to the general Indicia importer which is a complex merge to do at the moment).

2. I have a question actually @BirenRathod.
What branch is the Plant Portal dev site runnin?g, I thought we updated this recently but it isn't showing what I am expecting (e.g. Vice Country/Country attribute number is not displayed on import page edit tab)

**Comment by BirenRathod** [comment]
@andrewvanbreda 
Plant portal is running from dev branch. I just updated code on iform and client_helpers folders.

**Comment by andrewvanbreda** [comment]
@BirenRathod Hi, Thanks that looks up to date now, so I will configure it.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Hi Biren,
Am having problems with the performance of the dev warehouse. Sometimes it is taking ages to load pages and when I try and save a term (into location types) it is taking so long it doesn't even seem to work at all. Click Save and it looks like the next page is taking ages to load, nothing obvious to me in logs, and the item doesn't save?
Any thoughts?

**Comment by BirenRathod** [comment]
@andrewvanbreda 

I'm not sure, what is causing this? I just restarted the server, see if that make any difference.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Seems to still be doing same thing. I have to go out now, so we can look at this another time.

**Comment by BirenRathod** [comment]
@andrewvanbreda 
Did you check your connection? I have got no problem from my machine. or may be that particular page has got some problem. Could you send me the link, so I could check from my end too.

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod,
Yes might be an idea. Can you see what happens at your end if you create a term on this page called 
"Plant Portal Plot" and click Save. 
https://devwarehouse.indicia.org.uk/index.php/termlists_term/create/5

**Comment by andrewvanbreda** [comment]
@BirenRathod This still doesn't work, even if I use my emergency 3G dongle connection.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Note I have just done some other configuration tasks, you might be right, and this is limited to one screen. Any thoughts? There didn't seem to be anything in the log which is odd if it was a code issue.

**Comment by johnvanbreda** [comment]
I'll take a look in case it's a v2 issue.

**Comment by johnvanbreda** [comment]
Ok - I've found the issue. It relates to the queuing of changes to the new cache table attrs_json data field, which might need an update across many records if you change a term. I probably need to optimise a query so will look at that now.

**Comment by BirenRathod** [comment]
@johnvanbreda , @andrewvanbreda 

Sorry I couldn't able to message yesterday as my password expired. Yes, I found the bug too which John has just discovered. 
@johnvanbreda , to my surprise this was not throwing any error in the log too apart from this notice, "Trying to filter on unknown column wantColumns."

**Comment by johnvanbreda** [comment]
@andrewvanbreda I've applied a performance fix and updated the dev warehouse.

**Comment by andrewvanbreda** [comment]
@johnvanbreda @BirenRathod 
OK thanks. I noticed a Plant Portal Plot had been created already, so changed the name as a test.
The first time I did it, it hung again, although it did save the change this time when I manually re-loaded page.
Then I changed the name back and it was fine.
So I think best leave for now, and I will keep an eye on it. Thanks for the fix.

**Comment by andrewvanbreda** [comment]
@BirenRathod @sacrevert 
Biren, we should be able to get the Plant Portal site running now.
Is the Dev Warehouse running the latest development branch code?
Also can the iForm on the Plant Portal Dev site be updated to the latest code, I made some changes to fix compatibility with some general changes that had been introduced in Indicia (I have seen this working on my own machine now)

**Comment by BirenRathod** [comment]
@andrewvanbreda 

I have upgraded code today from dev branch on dev warehouse. Also, I updated code on PlantPortal site too.

**Comment by andrewvanbreda** [comment]
@BirenRathod @DavidRoy @sacrevert 
OK, thanks Biren. That is working much better than it was. However I am finding the actual import isn't creating the plot, not sure why that is, I will have a look, that works OK on my machine.
David/Oli: As noted this is now running much that it was. It isn't importing the actual records, am not sure why that is yet, however you can run through the Wizard. 
It might be of interest to you to try the importer yourself, even if the records are not actually getting imported. You can see the wizard, also the user warnings screen is present at the end of the Wizard, the import also runs, it is just rejecting the record I tried, not sure why.

**Comment by andrewvanbreda** [comment]
Actually looks like reports are missing, I will double-check these have been committed.

**Comment by andrewvanbreda** [comment]
@BirenRathod Looks like I forgot to commit some reports. I have done this now there is now a plant_portal in reports_for_prebuilt_forms that should be on the dev warehouse. It it is in the dev branch now.

**Comment by BirenRathod** [comment]
@andrewvanbreda 
if you are already planning to move this report into brc_reports folder, better do it now and I will pull code on dev warehouse.

**Comment by BirenRathod** [comment]
@andrewvanbreda 
Another reason to do that John has not included that folder in warehouse 2 reports folder. you need to move that to brc_report folder. let me know once you finish then I will pull code from brc_report.

**Comment by andrewvanbreda** [comment]
@BirenRathod That is a good point. This folder is not in brc_reports yet. I will need to change some paths in iForm code to do that though.
I can add that to my To Do list.
Is it possible to just have it in reports_for_prebuilt_forms for now

Thanks

**Comment by BirenRathod** [comment]
@andrewvanbreda 
I pulled the code of plantportal now.

**Comment by andrewvanbreda** [comment]
Thanks @BirenRathod. Still getting the same issue, but that might simply be that although the reports was A problem, it might not of been THE problem.
Will see if I can reproduce it on my own machine.

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod @DavidRoy @sacrevert 

I just looked at the Plant Portal importer again.

I think last time we spoke there were two problems stopping it working.

1. One of the problems was occurring on the dev site AND my machine.

2. One of the problems ONLY occurred on the BRC Plant Portal Dev site, my machine was fine running the same code.

As a result of this, me and Biren added a lot of logging to the site.

Number 1: I fixed a month or so ago but hasn't been deployed to Plant Portal Dev yet.

Number 2: wasn't fixed. However I just tried it and for no reason I know of, it seems to be working!

So, we need to deploy fix 1, (and get ride of the extra logging) and hope the number 2 keeps working.

@BirenRathod : is it possible to update the Plant Portal dev site iform/client_helpers to the dev branch again.
It is also possible to update the Dev warehousw with the latest dev branch code? Or if not the whole warehouse, just the Plant Portal Importer module should be enough.

Is it possible also to make a copy of the code before you update so we can go back if problem 2 stops working?
If this isn't possible then we will have to update and hope.

Andy

**Comment by BirenRathod** [comment]
@andrewvanbreda 
Here are my actions
1. I made another copy of iform module & pulled the code from develop branch.
2. Dev warehouse has upgraded on 31st Oct and I checked today again, it is up to date.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks Biren. I think actually this is working now, there is just one problem I accidently left a log message in that gets displayed (hence my confusion why I thought it wasn't working).
We can leave it in for now, it can just be removed during another update in the future.
