### ISSUE TITLE
Vascular plant card habitat at the record level

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#9]
Allow recording of habitat (standard iRecord options- at the record level)
See #3 for umbrella issue.

@DavidRoy David asked:
Does habitat make sense as a grid square attribute?  I note that this field is on the BSBI record form coversheet.  Do recorders use this, for example, to just record woodlands in a grid square.  Then submit another ëcardí for grasslands?

Response from @sacrevert 
For vascular plants, it would be best as a list of habitats. Not sure how this would work with the two-tier EUNIS approach currently used. Unless one was just able to list multiple habitats at either level, without worrying about nesting?

**Comment by johnvanbreda** [comment]
Listing multiple habitats at the per-record level might make the user interface quite complex/messy?

**Comment by DavidRoy** [comment]
I think this would have to be a single value field to be usable.  Oli and I will define the list

**Comment by sacrevert** [comment]
@DavidRoy @johnvanbreda On reflection, I wonder whether this is worth the effort. As far as I am aware the habitat attributes captured at the physical card level have never been digitised, and even if they were in the BRC Oracle database, there is no corresponding field in the BSBI DDb (afaik). I propose putting this issue on hold - at least until Kevin and Tom comment (I seem recall Kev was not very bothered about this).

**Comment by johnvanbreda** [comment]
Ok, I will remove the habitat field - we can add it back if needs be.
